#!/usr/bin/env bun

/**
 * Version Commit Helper - Handles version embedding and commit workflow
 *
 * This script solves the version embedding artifact problem by:
 * 1. Running version embedding
 * 2. Auto-committing the artifacts with proper attribution
 * 3. Ensuring clean working tree for pushes
 *
 * Used in release workflows to maintain checklist compliance.
 */

import { execSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";

function safeExec(command: string): string {
  try {
    return execSync(command, { encoding: "utf-8", cwd: process.cwd() }).toString().trim();
  } catch (error) {
    console.error(`Command failed: ${command}`);
    throw error;
  }
}

function getVersionFromFile(): string {
  try {
    return safeExec("cat VERSION").trim();
  } catch (error) {
    console.error("❌ Could not read VERSION file");
    throw error;
  }
}

function checkGitStatus(): { isClean: boolean; hasVersionArtifacts: boolean; files: string[] } {
  const status = safeExec("git status --porcelain");

  if (!status) {
    return { isClean: true, hasVersionArtifacts: false, files: [] };
  }

  const lines = status.split("\n").filter((l) => l.trim());
  const modifiedFiles = lines.map((line) => line.substring(3));

  const versionFiles = [
    "src/cli/brooklyn.ts",
    "src/core/config.ts",
    "src/shared/build-config.ts",
    "src/generated/build-signature.ts",
  ];

  const hasVersionArtifacts = modifiedFiles.some((file) => versionFiles.includes(file));

  return {
    isClean: lines.length === 0,
    hasVersionArtifacts,
    files: modifiedFiles,
  };
}

async function embedVersion(): Promise<void> {
  console.log("🔧 Embedding version in source files...");

  try {
    execSync("bun run version:embed", { stdio: "inherit" });
    console.log("✅ Version embedding completed");
  } catch (error) {
    console.error("❌ Version embedding failed");
    throw error;
  }
}

async function commitVersionArtifacts(version: string): Promise<void> {
  const status = checkGitStatus();

  if (status.isClean) {
    console.log("✅ No version artifacts to commit - working tree is clean");
    return;
  }

  if (!status.hasVersionArtifacts) {
    console.log("⚠️  Working tree has changes but no version artifacts detected");
    console.log("Files with changes:", status.files.join(", "));
    console.log("Please handle these changes manually before proceeding");
    process.exit(1);
  }

  console.log("📦 Committing version artifacts...");

  // Stage version-related files only
  const versionFiles = [
    "src/cli/brooklyn.ts",
    "src/core/config.ts",
    "src/shared/build-config.ts",
    "src/generated/build-signature.ts",
  ];

  for (const file of versionFiles) {
    try {
      // Check if file exists and has changes
      const fileStatus = safeExec(`git status --porcelain -- ${file}`);
      if (fileStatus) {
        execSync(`git add ${file}`);
        console.log(`📝 Staged ${file}`);
      }
    } catch (error) {
      // File might not exist or have changes - that's OK
    }
  }

  // Create commit with proper attribution
  const commitMessage = `chore: embed version ${version} for release preparation

🎯 Changes:
- Updated version constants in CLI, config, and build files
- Generated build signature for deterministic binary identification
- Prepared source files for release build process

📦 Version: ${version}
🔧 Automated: Version embedding artifacts

Generated by Paris Brooklyn ([Claude Code](https://claude.ai/code)) under supervision of [@3leapsdave](https://github.com/3leapsdave)

Co-Authored-By: Paris Brooklyn <noreply@fulmenhq.dev>
Authored-By: Dave Thompson <dave.thompson@3leaps.net> [@3leapsdave](https://github.com/3leapsdave)`;

  try {
    // Write commit message to temp file
    const tempFile = "/tmp/brooklyn-version-commit.txt";
    await fs.writeFile(tempFile, commitMessage);

    // Commit with the message
    execSync(`git commit -F ${tempFile}`, { stdio: "inherit" });

    // Clean up temp file
    await fs.unlink(tempFile).catch(() => {}); // Ignore errors

    console.log(`✅ Version ${version} artifacts committed successfully`);
  } catch (error) {
    console.error("❌ Failed to commit version artifacts");
    throw error;
  }
}

async function versionCommitWorkflow(
  options: { embedOnly?: boolean; commitOnly?: boolean } = {},
): Promise<void> {
  const { embedOnly = false, commitOnly = false } = options;

  const version = getVersionFromFile();
  console.log(`🚀 Version Commit Workflow for v${version}`);
  console.log("");

  // Check initial status
  const initialStatus = checkGitStatus();

  if (!commitOnly) {
    // Step 1: Embed version
    await embedVersion();
  }

  if (!embedOnly) {
    // Step 2: Commit artifacts
    await commitVersionArtifacts(version);

    // Step 3: Verify final state
    const finalStatus = checkGitStatus();
    if (finalStatus.isClean) {
      console.log("");
      console.log("🎉 Version commit workflow completed successfully!");
      console.log(`📦 Version ${version} is ready for release`);
      console.log("✅ Working tree is clean - ready for push operations");
    } else {
      console.log("");
      console.log("⚠️  Warning: Working tree still has uncommitted changes");
      console.log("Files:", finalStatus.files.join(", "));
      console.log("Please review and handle these changes manually");
    }
  }
}

// Handle command line usage
if (import.meta.main) {
  const args = process.argv.slice(2);
  const embedOnly = args.includes("--embed-only");
  const commitOnly = args.includes("--commit-only");
  const help = args.includes("--help") || args.includes("-h");

  if (help) {
    console.log("Version Commit Helper");
    console.log("");
    console.log("Usage: bun scripts/version-commit.ts [options]");
    console.log("");
    console.log("This script handles version embedding and commit workflow:");
    console.log("1. Embeds current VERSION into source files");
    console.log("2. Commits version artifacts with proper attribution");
    console.log("3. Ensures clean working tree for pushes");
    console.log("");
    console.log("Options:");
    console.log("  --embed-only     Only run version embedding, skip commit");
    console.log("  --commit-only    Only commit existing version artifacts");
    console.log("  --help, -h       Show this help");
    console.log("");
    console.log("Examples:");
    console.log("  bun scripts/version-commit.ts                  # Full workflow");
    console.log("  bun scripts/version-commit.ts --embed-only     # Just embed");
    console.log("  bun scripts/version-commit.ts --commit-only    # Just commit");
    console.log("");
    process.exit(0);
  }

  versionCommitWorkflow({ embedOnly, commitOnly })
    .then(() => {
      process.exit(0);
    })
    .catch((error) => {
      console.error("❌ Version commit workflow failed:", error.message);
      process.exit(1);
    });
}

export { versionCommitWorkflow };
